[versions]
morphe-patcher = "1.5.1"
instagram-morphe-patches-library = "1.0.0"
#noinspection GradleDependency
smali = "b6365a84f4"
gson = "2.13.2"
annotation = "1.9.1"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
morphe-patches-library = { module = "app.morphe:instagram-morphe-patches-library", version.ref = "instagram-morphe-patches-library" }
morphe-extensions-library = { module = "app.morphe:instagram-morphe-extensions-library", version.ref = "instagram-morphe-patches-library" }

[plugins]
android-library = { id = "com.android.library" }
